development:
  check_sites:
    class: ScheduleSiteCheckJob
    schedule: every 30 seconds

production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
  cleanup_old_results:
    class: CleanupCheckResultsJob
    schedule: every day at 3am
